;/*FB_PKG_DELIM*/

__d("CometEventPermalinkTab",["$InternalEnum"],(function(t,n,r,o,a,i){var e=n("$InternalEnum")({ABOUT:"about",DISCUSSION:"discussion",BRACKETS:"brackets",BROADCASTS:"broadcasts",PARTICIPANTS:"participants",STANDINGS:"standings",VIDEOS:"videos",PAID_ACCESS:"paid_access"}),l=e;i.default=l}),66);
__d("EventCometActionContextDefault",[],(function(t,n,r,o,a,i){"use strict";var e={event_action_history:[]};i.default=e}),66);
__d("EventCometActionContext",["EventCometActionContextDefault","react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=s.createContext(r("EventCometActionContextDefault"));l.default=u}),98);
__d("EventCometActionLoggerUtils",["CometRouteURL"],(function(t,n,r,o,a,i,l){"use strict";var e={mechanism:"unknown",surface:"unknown"},s=3;function u(e,t){var n=[].concat(e.event_action_history||[]);n.length>=s&&(n=n.slice(n.length-s+1));var r=c(e);return n.push({event_tracking:r.event_tracking,extra_data:r.extra_data,mechanism:t.mechanism,surface:t.surface}),babelHelpers.extends({},e,{event_action_history:n})}function c(t){var n=t.event_action_history;return n==null||n[n.length-1]==null?e:n.length>=2?n[n.length-2]:n[n.length-1]}function d(){var e=o("CometRouteURL").useRouteURL(),t=/\/events\/\d+/;return t.test(e)?"permalink":e.includes("/events/calendar")?"bookmark_calendar":e.includes("/events")?"bookmark":e.includes("profile.php")?"timeline":"newsfeed"}l.createForNewSurface=u,l.getLastActionHistoryEntry=c,l.useExtractEventComposerSurface=d}),98);
__d("FBPayUPLSessionIDGenerator",["uuidv4"],(function(t,n,r,o,a,i,l){"use strict";var e="upl";function s(){var t=[e,Date.now(),r("uuidv4")()];return t.join("_")}l.sessionIDGenerator=s}),98);
__d("FDSCalendarFilled20Icon",["cr:13822"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:13822")}),98);
__d("FDSCalendarFilled20PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("481118"),20),u=e;l.default=u}),98);
__d("FDSStarFilled20Icon",["cr:15698"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:15698")}),98);
__d("FDSStarFilled20PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("479327"),20),u=e;l.default=u}),98);
__d("RelayFBResponseCache",["RelayRuntime"],(function(t,n,r,o,a,i){"use strict";var e=n("RelayRuntime").QueryResponseCache,l=10,s=300*1e3;a.exports=new e({size:l,ttl:s})}),null);
__d("XCometEventPermalinkControllerRouteBuilder",["jsRouteBuilder"],(function(t,n,r,o,a,i,l){var e=r("jsRouteBuilder")("/events/{event_id}/{?child_event_id}/",Object.freeze({active_tab:"about",show_created_event_toast:!1,hide_invite_flow_filter_groups:!1}),void 0),s=e;l.default=s}),98);
__d("castToEnum",[],(function(t,n,r,o,a,i){"use strict";function e(e,t,n){for(var r=Object.keys(t),o=0;o<r.length;o++)if(t[r[o]]===e)return t[r[o]];return n}i.default=e}),66);
__d("mapMapToArray",[],(function(t,n,r,o,a,i){"use strict";function e(e,t){var n=[],r=0;for(var o of e){var a=o[0],i=o[1];n.push(t(i,a,r,e)),r++}return n}i.default=e}),66);
__d("useBaseDynamicEntryPointDialog",["CometDialogContext","CometRelay","CometSuspendedDialogImpl.react","clearTimeout","react","react-compiler-runtime","setTimeout","tracePolicyFromResource","useCometRelayEntrypointContextualEnvironmentProvider"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=e,c=u.useCallback,d=u.useContext,m=u.useEffect,p=u.useRef;function _(e){var t=o("react-compiler-runtime").c(17),n=e.entryPoint,a=e.environmentProvider,i=e.onClose,l=e.otherProps,u=e.overrideRelayEnv,c=e.preloadedEntryPoint,d=e.preloadParams,_=o("CometRelay").useEntryPointLoader(a,n),f=_[0],g=_[1],h=_[2],y=f!=null?f:c,C=p(null),b,v;t[0]!==h||t[1]!==y.isDisposed||t[2]!==d||t[3]!==c||t[4]!==g||t[5]!==f?(b=function(){return C.current!=null&&(r("clearTimeout")(C.current),C.current=null),y.isDisposed&&g(d),(function(){C.current=r("setTimeout")(function(){f?h():c.dispose(),C.current=null},6e4)})},v=[h,y.isDisposed,c,d,g,f],t[0]=h,t[1]=y.isDisposed,t[2]=d,t[3]=c,t[4]=g,t[5]=f,t[6]=b,t[7]=v):(b=t[6],v=t[7]),m(b,v);var S;t[8]!==i||t[9]!==l?(S=babelHelpers.extends({},l,{onClose:i}),t[8]=i,t[9]=l,t[10]=S):S=t[10];var R=S,L;t[11]!==c||t[12]!==R?(L=s.jsx(o("CometRelay").EntryPointContainer,{entryPointReference:c,props:R}),t[11]=c,t[12]=R,t[13]=L):L=t[13];var E=L,k;return t[14]!==E||t[15]!==u?(k=u!=null?s.jsx(o("CometRelay").RelayEnvironmentProvider,{environment:u,children:E}):E,t[14]=E,t[15]=u,t[16]=k):k=t[16],k}function f(e,t,n,a){var i=o("react-compiler-runtime").c(7),l=r("useCometRelayEntrypointContextualEnvironmentProvider")(a),s=d(r("CometDialogContext")),u;return i[0]!==s||i[1]!==e||i[2]!==l||i[3]!==n||i[4]!==a||i[5]!==t?(u=function(u,c,d,m,p){var i=o("CometRelay").loadEntryPoint(l,e,u),f=function(){for(var e=arguments.length,t=new Array(e),n=0;n<e;n++)t[n]=arguments[n];var r=t;d&&d.apply(void 0,r),i.dispose()};s(r("CometSuspendedDialogImpl.react"),{dialog:_,dialogProps:{entryPoint:e,environmentProvider:l,otherProps:c,overrideRelayEnv:a,preloadedEntryPoint:i,preloadParams:u},fallback:n},{loadType:"entrypoint",preloadTrigger:t,tracePolicy:m!=null?m:r("tracePolicyFromResource")("comet.dialog",e.root)},f,{replaceCurrentDialog:p})},i[0]=s,i[1]=e,i[2]=l,i[3]=n,i[4]=a,i[5]=t,i[6]=u):u=i[6],u}l.default=f}),98);
__d("useCometDynamicEntryPointDialog",["FDSDialogLoadingState.react","react","useBaseDynamicEntryPointDialog"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=function(t){return s.jsx(r("FDSDialogLoadingState.react"),{onClose:t})};function c(e,t,n,o){return r("useBaseDynamicEntryPointDialog")(e,t,n!=null?n:u,o)}l.default=c}),98);
__d("useShallowEqualMemo",["shallowEqual","useCustomEqualityMemo"],(function(t,n,r,o,a,i,l){"use strict";function e(e){return r("useCustomEqualityMemo")(e,r("shallowEqual"))}l.default=e}),98);